name: AntiBuilder
description: Simple plugin for protect lobbys... against break and place blocks.
author: AuchenDevs
main: me.craciu25yt.AntiBuilder.Main
version: 0.0.2
url: https://github.com/AuchenDevs-mc/AntiBuilder
commands:
  example:
    aliases: ["ex"]
    description: "This is an example plugin."